---
# tasks file for apache

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: apache

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: apache

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: apache

- name: Create Apache defaults file
  template: >
    src=apache2.default.j2
    dest=/etc/default/apache2
    owner=root
    group=root
    mode=0644
  notify: restart apache
  tags: apache

- name: Create Apache envvars configuration file
  template: >
    src=envvars.j2
    dest=/etc/apache2/envvars
    owner=root
    group=root
    mode=0644
  notify: restart apache
  tags: apache

- name: Create Apache ports configuration file
  template: >
    src=ports.conf.j2
    dest=/etc/apache2/ports.conf
    owner=root
    group=root
    mode=0644
  notify: restart apache
  tags: apache

- name: Create Apache main configuration file
  template: >
    src=apache2.conf.j2
    dest=/etc/apache2/apache2.conf
    owner=root
    group=root
    mode=0644
  notify: restart apache
  tags: apache

- name: Ensure Apache service is started and enabled on boot
  service: name={{ apache_service_name }} state=started enabled=yes
  tags: apache
