---
# handlers file for apache

- name: restart apache
  service: name={{ apache_service_name }} state=restarted
  tags: apache

- name: reload apache
  service: name={{ apache_service_name }} state=reloaded
  tags: apache
